### ISSUE TITLE
make compatible with locally hosted llama.cpp?

### ISSUE THREAD

**Issue by AmFerra** [davidgm3/llama2-discord-bot#1]
it would require a bit of change, but might not be too hard

**Comment by davidgonmar** [comment]
Hey! Did not see this until now. Not sure if I'll do this, but might be interesting to try:)

**Comment by davidgonmar** [comment]
> it would require a bit of change, but might not be too hard

Hey! Looked into it and got it (you can still use Replicate, but also download the model binary and run it locally) Let me know what you think!
